---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8

inputs:
  - name: git-repo

run:
  path: git-repo/ci/scripts/acceptance-tests.sh

params:
  API_HOST:
  API_PORT:
  USERNAME:
  PASSWORD:
  CLIENT_ID:
  CLIENT_SECRET:
  DEFAULT_ORG:
  DEFAULT_SPACE:
  SKIP_SSL_VALIDATION:
