---
platform: linux
inputs:
  - name: git-repo
outputs:
  - name: distribution-repository
caches:
  - path: maven
  - path: gradle
run:
  path: bash
  args:
    - -ec
    - |
      ${PWD}/git-repo/ci/scripts/build-project.sh
