# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: sc-app-broker-{{ .Branch }}

      - run:
          name: "Download dependencies"
          command: ./gradlew assemble

      - save_cache:
          paths:
            - ~/.gradle
          key: sc-app-broker-{{ .Branch }}

      - run:
          name: "Run tests"
          command: ./gradlew codeCoverageReport --stacktrace --info --continue

      - run:
          name: "Upload tests results"
          command: bash <(curl -s https://codecov.io/bash)
