# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx2048m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx512m -Xmx2048m" -Dorg.gradle.daemon=false'
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: sc-app-broker-{{ .Branch }}

      - run:
          name: "Download dependencies"
          command: ./gradlew assemble

      - save_cache:
          paths:
            - ~/.gradle
          key: sc-app-broker-{{ .Branch }}

      - run:
          name: "Disable Gradle daemon"
          command: touch ~/.gradle/gradle.properties && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

      - run:
          name: "Run tests"
          command: ./gradlew clean codeCoverageReport --stacktrace --info --continue

      - run:
          name: "Aggregate test results"
          when: always
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*" -exec cp {} ~/junit/ \;

      - run:
          name: "Upload tests coverage"
          command: bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: ~/junit/
          destination: artifacts

      - store_test_results:
          path: ~/junit/
          destination: testartifacts