# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx2048m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx512m -Xmx2048m" -Dorg.gradle.daemon=false'
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: sc-app-broker-{{ .Branch }}

      - run:
          name: "Download dependencies"
          command: ./gradlew assemble

      - save_cache:
          paths:
            - ~/.gradle
          key: sc-app-broker-{{ .Branch }}

      - run:
          name: "Disabling Gradle daemon"
          command: touch ~/.gradle/gradle.properties && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

      - run:
          name: "Run tests"
          command: ./gradlew clean codeCoverageReport --stacktrace --debug --continue

      - run:
          name: "Upload tests results"
          command: bash <(curl -s https://codecov.io/bash)
