spring:
  cloud:
    openservicebroker:
      catalog:
        services:
        - id: example-service
          name: example
          description: A simple example
          bindable: true
          tags:
          - example
          plans:
          - id: simple-plan
            bindable: true
            name: standard
            description: A simple plan
            free: true
    appbroker:
      apps:
        - name: broker-sample-app
          path: classpath:demo.jar
      deployer:
        cloudfoundry:
          api-host: run.pivotal.io
          api-port: 443
          username: admin
          password: adminpass
          default-org: test
          default-space: development
          skip-ssl-validation: true