spring:
  cloud:
    openservicebroker:
      catalog:
        services:
        - id: example-service
          name: example
          description: A simple example
          bindable: true
          tags:
          - example
          plans:
          - id: simple-plan
            bindable: true
            name: standard
            description: A simple plan
            free: true
    appbroker:
      apps:
        - name: broker-sample-app
          path: classpath:demo.jar
      deployer:
        cloudfoundry:
          apiHost: run.pivotal.io
          apiPort: 443
          username: admin
          password: adminpass
          defaultOrg: test
          defaultSpace: development
          skipSslValidation: true