plugins {
	id 'java'
	id 'org.springframework.boot' version '2.6.7'
	id 'io.spring.dependency-management' version '1.1.7'
}

ext {
// osb-cmdb doesn't lock spring version and leaves it to springboot (unless meeting issues)
//	springFrameworkVersion = project.findProperty("springFrameworkVersion") ?: "5.2.11.RELEASE"
	openServiceBrokerVersion = "3.5.1"
	cfJavaClientVersion = "5.8.0.RELEASE"
	cfJavaClientForkedVersion = "0b299d2b792207b52a944d50aa459c247c564597"
	junitPlatformLauncherVersion = "1.6.1"
	wiremockVersion = "2.27.2"
}

version='1.9.0-SNAPSHOT'
group = 'com.orange.oss'
description = 'Osb cmdb'


java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(8)
	}
}

// See https://docs.spring.io/spring-boot/gradle-plugin/packaging.html#packaging-executable.configuring.main-class
springBoot {
	mainClass = 'com.orange.oss.osbcmdb.OsbCmdbApplication'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation "org.springframework.cloud:spring-cloud-starter-open-service-broker:${openServiceBrokerVersion}"
	implementation("org.cloudfoundry:cloudfoundry-operations:${cfJavaClientVersion}")
	implementation("org.cloudfoundry:cloudfoundry-client-reactor:${cfJavaClientVersion}")
	implementation("org.apache.commons:commons-text:1.9")
	implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.2")
	implementation("de.skuzzle:semantic-version:2.1.1")

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly "org.junit.platform:junit-platform-launcher:${junitPlatformLauncherVersion}"

	testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
	testImplementation("org.junit.jupiter:junit-jupiter-api")
	testImplementation("org.springframework.boot:spring-boot-starter-test") {
		//See https://github.com/junit-team/junit5/issues/2105#issuecomment-609077749
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
	testImplementation("org.springframework.security:spring-security-test")
	testImplementation("io.projectreactor:reactor-test")
	testImplementation("org.assertj:assertj-core")
	//For custom workflows
	testImplementation("org.mockito:mockito-core")
	testImplementation("org.mockito:mockito-junit-jupiter")
	testImplementation("io.rest-assured:rest-assured")
	testImplementation("com.github.tomakehurst:wiremock:${wiremockVersion}")


}


tasks.named('test') {

	//Propagate tags from gradle command line to fine tune test selection
	//See https://javabydeveloper.com/run-tag-specific-junit-5-tests-from-gradle-command/
	String itagsProp = System.getProperty("includeTags")
	String etagsProp = System.getProperty("excludeTags")


	useJUnitPlatform{
		if (itagsProp !=null) {
			String[] itags = itagsProp.split(",");
			includeTags  itags
		}
		if (etagsProp != null) {
			String[] etags = etagsProp.split(",");
			excludeTags  etags
		}
	}

	useJUnitPlatform()

}
