#spring:
#  cloud:
#    openservicebroker:
#      Open Service Broker configuration properties are configured test setup
#    appbroker:
#      services:
#        App Broker services configuration properties are configured individual test cases
#      deployer:
#        App Broker deployer configuration properties are configured test setup

logging:
  level:
    cloudfoundry-client: DEBUG
    cloudfoundry-client.operations: DEBUG
#    cloudfoundry-client.request: DEBUG
#    cloudfoundry-client.response: DEBUG

    org.springframework.cloud.appbroker: DEBUG
    org.springframework.cloud.appbroker.deployer: DEBUG
    org.springframework.cloud.appbroker.workflow: DEBUG
    org.springframework.cloud.appbroker.workflow.instance: DEBUG
    org.springframework.cloud.appbroker.deployer.cloudfoundry: DEBUG
    org.springframework.cloud.appbroker.deployer.cloudfoundry.CloudFoundryAppDeployer: DEBUG
    org.springframework.cloud.servicebroker: DEBUG
